Repository YAPP-Github/TnT-iOS, pull requests merged in 2025-01, with the labels that each got.

#14 [Setting] Tuist 세팅
  .gitignore
  TnT/.gitignore
  TnT/.mise.toml
  TnT/Project.swift
  TnT/Projects/DI/Project.swift
  TnT/Projects/DI/Sources/DISoureDummy.swift
  TnT/Projects/Data/Project.swift
  TnT/Projects/Data/Sources/DataSoureDummy.swift
  TnT/Projects/DesignSystem/Project.swift
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Contents.json
  TnT/Projects/DesignSystem/Sources/DesignSystemSoureDummy.swift
  TnT/Projects/Domain/Project.swift
  TnT/Projects/Domain/Sources/DomainSoureDummy.swift
  TnT/Projects/Presentation/Project.swift
  TnT/Projects/Presentation/Sources/PresentationSoureDummy.swift
  TnT/Projects/TnTApp/Project.swift
  TnT/Projects/TnTApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  TnT/Projects/TnTApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  TnT/Projects/TnTApp/Resources/Assets.xcassets/Contents.json
  TnT/Projects/TnTApp/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  TnT/Projects/TnTApp/Sources/Application/AppDelegate.swift
  TnT/Projects/TnTApp/Sources/Application/SceneDelegate.swift
  TnT/Projects/TnTApp/Sources/ContentView.swift
  TnT/Projects/TnTApp/Sources/TnTApp.swift
  TnT/Projects/TnTApp/Support/Info.plist
  TnT/Tuist/Package.resolved
  TnT/Tuist/Package.swift
  TnT/Tuist/ProjectDescriptionHelpers/Configuration/Configuration+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Dependency/Dependency+Teplates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Dependency/DependencyInformation.swift
  TnT/Tuist/ProjectDescriptionHelpers/Dependency/ExternalDependency.swift
  TnT/Tuist/ProjectDescriptionHelpers/Environment/Environment.swift
  TnT/Tuist/ProjectDescriptionHelpers/Project/Project+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Project/Scheme+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Project/Target+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Script/Script.swift
  TnT/Workspace.swift
  TnT/swiftlint.yml
Labels: Setting

#16 [TNT-124] 디자인 시스템 관련 코드 작성
  TnT/Projects/DesignSystem/Sources/Color+DesignSystem.swift
  TnT/Projects/DesignSystem/Sources/DesignSystemSoureDummy.swift
  TnT/Projects/DesignSystem/Sources/Font+DesignSystem.swift
  TnT/Projects/DesignSystem/Sources/Image+DesignSystem.swift
  TnT/Projects/TnTApp/Support/Info.plist
  TnT/TnT/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  TnT/TnT/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  TnT/TnT/Resources/Assets.xcassets/Contents.json
  TnT/TnT/Resources/LaunchScreen.storyboard
  TnT/TnT/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  TnT/TnT/Sources/ContentView.swift
  TnT/TnT/Sources/TnTApp.swift
  TnT/TnT/Tests/TnTTests.swift
  TnT/Tuist/Config/.swiftlint.yml
  TnT/Tuist/Package.swift
  TnT/Tuist/ProjectDescriptionHelpers/Environment/Environment.swift
  TnT/Tuist/ProjectDescriptionHelpers/Project/Target+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Script/Script.swift
Labels: Feat

#20 [TNT-139] TTextField, TTextEditor 컴포넌트 코드 작성
  TnT/Projects/DesignSystem/Sources/Components/Divider/TDivider.swift
  TnT/Projects/DesignSystem/Sources/Components/TextField/TTextEditor.swift
  TnT/Projects/DesignSystem/Sources/Components/TextField/TTextField.swift
  TnT/Projects/DesignSystem/Sources/DesignSystem/Font+DesignSystem.swift
  TnT/Projects/DesignSystem/Sources/Utility/TextUtility.swift
  TnT/Tuist/Config/Info.plist
Labels: Feat

#22 [Feat] Button, Navigation 컴포넌트 구현
  TnT/Projects/DesignSystem/Sources/Button/TBottomButton.swift
  TnT/Projects/DesignSystem/Sources/Button/TButton.swift
  TnT/Projects/DesignSystem/Sources/Button/TButtonInfo.swift
  TnT/Projects/DesignSystem/Sources/Button/TIcnButton.swift
  TnT/Projects/DesignSystem/Sources/Navigation/TNavigation.swift
  TnT/Tuist/ProjectDescriptionHelpers/Configuration/Configuration+Templates.swift
Labels: ✨Feat

#21 [TNT-139] TControlButton, TPopUp 컴포넌트 코드 작성
  TnT/Projects/DesignSystem/Sources/Components/Control/TControlButton.swift
  TnT/Projects/DesignSystem/Sources/Components/Control/TToggleStyle.swift
  TnT/Projects/DesignSystem/Sources/Components/PopUp/TPopUpAlertState.swift
  TnT/Projects/DesignSystem/Sources/Components/PopUp/TPopUpAlertView.swift
  TnT/Projects/DesignSystem/Sources/Components/PopUp/TPopUpModifier.swift
  TnT/Projects/DesignSystem/Sources/Utility/EquatableClosure.swift
Labels: ✨Feat

#24 [TNT-142] 트레이너/트레이니 선택 화면, 프로필 만들기 화면 작성
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_profile_image.imageset/img_default_profile_image.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_profile_image.imageset/img_default_profile_image@2x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_profile_image.imageset/img_default_profile_image@3x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainee_image.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainee_image.imageset/basic profile_trainee.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainee_image.imageset/basic profile_trainee@2x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainee_image.imageset/basic profile_trainee@3x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainer_image.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainer_image.imageset/basic profile_trainer.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainer_image.imageset/basic profile_trainer@2x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_default_trainer_image.imageset/basic profile_trainer@3x.png
  TnT/Projects/DesignSystem/Sources/Components/TextField/TTextField.swift
  TnT/Projects/DesignSystem/Sources/DesignSystem/Image+DesignSystem.swift
  TnT/Projects/Domain/Sources/Entity/UserType.swift
  TnT/Projects/Domain/Sources/Policy/UserPolicy.swift
  TnT/Projects/Domain/Sources/Utility/TextValidator.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/CreateProfile/CreateProfileFeature.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/CreateProfile/CreateProfileView.swift
  TnT/Projects/Presentation/Sources/Onboarding/UserTypeSelection/UserTypeSelectionFeature.swift
  TnT/Projects/Presentation/Sources/Onboarding/UserTypeSelection/UserTypeSelectionView.swift
  TnT/Projects/TnTApp/Sources/TnTApp.swift
  TnT/Tuist/Config/.swiftlint.yml
Labels: ✨Feat

#27 [TNT-163] NetworkService 작성
  TnT/Projects/Data/Sources/DataSoureDummy.swift
  TnT/Projects/Data/Sources/Network/Foundation/HTTPMethod.swift
  TnT/Projects/Data/Sources/Network/Foundation/MultipartItem.swift
  TnT/Projects/Data/Sources/Network/Foundation/NetworkError.swift
  TnT/Projects/Data/Sources/Network/Foundation/ParameterEncoding.swift
  TnT/Projects/Data/Sources/Network/Foundation/RequestTask.swift
  TnT/Projects/Data/Sources/Network/Foundation/TargetType.swift
  TnT/Projects/Data/Sources/Network/Interceptor/Interceptor.swift
  TnT/Projects/Data/Sources/Network/Interceptor/InterceptorPipeline.swift
  TnT/Projects/Data/Sources/Network/NetworkService.swift
  TnT/Projects/Data/Sources/Network/Utility/Data+.swift
  TnT/Projects/Data/Sources/Network/Utility/JSONDecoder+.swift
Labels: ✨Feat

#28 [TNT-163] Interceptor 구현체, KeyChainManager 추가
  TnT/Projects/Data/Sources/LocalStorage/KeyChainManager.swift
  TnT/Projects/Data/Sources/Network/Interceptor/Implements/AuthToken.swift
  TnT/Projects/Data/Sources/Network/Interceptor/Implements/Caching.swift
  TnT/Projects/Data/Sources/Network/Interceptor/Implements/Logging.swift
  TnT/Projects/Data/Sources/Network/Interceptor/Implements/ResponseValidator.swift
  TnT/Projects/Data/Sources/Network/Interceptor/Implements/Retry.swift
Labels: ✨Feat

#29 [TNT-80] Static Library에서도 Preview를 사용 가능하도록 Tuist 수정
  TnT/Projects/DI/Project.swift
  TnT/Projects/Data/Project.swift
  TnT/Projects/DesignSystem/Project.swift
  TnT/Projects/DesignSystem/Sources/Button/TBottomButton.swift
  TnT/Projects/Domain/Project.swift
  TnT/Projects/Domain/Sources/DomainSoureDummy.swift
  TnT/Projects/Presentation/Project.swift
  TnT/Projects/Presentation/Sources/PresentationSoureDummy.swift
  TnT/Projects/TnTApp/Project.swift
  TnT/Projects/TnTApp/Sources/ContentView.swift
  TnT/Tuist.swift
  TnT/Tuist/Package.swift
  TnT/Tuist/ProjectDescriptionHelpers/Configuration/Configuration+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Dependency/Dependency+Teplates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Dependency/DependencyInformation.swift
  TnT/Tuist/ProjectDescriptionHelpers/Environment/Environment.swift
  TnT/Tuist/ProjectDescriptionHelpers/Project/Project+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Project/Scheme+Templates.swift
  TnT/Tuist/ProjectDescriptionHelpers/Project/Target+Templates.swift
  TnT/Workspace.swift
  TnT/graph.png
Labels: ⚙️Setting

#34 [Refactor] TBotton 오류 수정
  TnT/Projects/DesignSystem/Sources/Button/TButton.swift
Labels: 🧹Chore

#35 [TNT-142] Domain - UserUseCase 관련 로직 작성
  TnT/Projects/DesignSystem/Sources/Components/DatePickerView/TDatePickerView.swift
  TnT/Projects/DesignSystem/Sources/Components/PageIndicator/TPageIndicator.swift
  TnT/Projects/DesignSystem/Sources/Components/TextField/TTextEditor.swift
  TnT/Projects/DesignSystem/Sources/Components/TitleHeader/TInfoTitleHeader.swift
  TnT/Projects/DesignSystem/Sources/Constants/TrainingPurposeText.swift
  TnT/Projects/DesignSystem/Sources/Constants/UnitText.swift
  TnT/Projects/DesignSystem/Sources/Constants/UserTypeText.swift
  TnT/Projects/Domain/Sources/Entity/TrainingPurpose.swift
  TnT/Projects/Domain/Sources/Entity/UserSignUpInfo.swift
  TnT/Projects/Domain/Sources/Entity/UserType.swift
  TnT/Projects/Domain/Sources/Extension/Date+.swift
  TnT/Projects/Domain/Sources/Extension/String+.swift
  TnT/Projects/Domain/Sources/Policy/TDateFormat.swift
  TnT/Projects/Domain/Sources/Policy/UserPolicy.swift
  TnT/Projects/Domain/Sources/UseCase/UserUseCase.swift
  TnT/Projects/Domain/Sources/Utility/TDateFormatUtility.swift
  TnT/Projects/Domain/Sources/Utility/TextValidator.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/CreateProfile/CreateProfileFeature.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/CreateProfile/CreateProfileView.swift
  TnT/Projects/Presentation/Sources/Utility/KeyboardDismiss.swift
Labels: ✨Feat

#36 [TNT-142] Trainee 회원가입정보 입력 플로우 화면 작성
  TnT/Projects/DesignSystem/Sources/Components/DatePickerView/TDatePickerView.swift
  TnT/Projects/Presentation/Sources/Onboarding/CreateProfile/CreateProfileFeature.swift
  TnT/Projects/Presentation/Sources/Onboarding/CreateProfile/CreateProfileView.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/CreateProfile/CreateProfileView.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/TraineeBasicInfoInput/TraineeBasicInfoInputFeature.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/TraineeBasicInfoInput/TraineeBasicInfoInputView.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/TraineePrecautionInput/TraineePrecautionInputFeature.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/TraineePrecautionInput/TraineePrecautionInputView.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/TraineeTrainingPurpose/TraineeTrainingPurposeFeature.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/TraineeTrainingPurpose/TraineeTrainingPurposeView.swift
  TnT/Projects/Presentation/Sources/Onboarding/UserTypeSelection/UserTypeSelectionView.swift
Labels: ✨Feat

#38 [TNT-163] UserRepository 작성, NetworkService 로직 보완
  TnT/Projects/Data/Sources/Network/Foundation/MultipartItem.swift
  TnT/Projects/Data/Sources/Network/Foundation/RequestTask.swift
  TnT/Projects/Data/Sources/Network/NetworkService.swift
  TnT/Projects/Data/Sources/Network/Service/Config/Config.swift
  TnT/Projects/Data/Sources/Network/Service/User/UserRepositoryImpl.swift
  TnT/Projects/Data/Sources/Network/Service/User/UserTargetType.swift
  TnT/Projects/Data/Sources/Network/Utility/UIImage+.swift
  TnT/Projects/Domain/Sources/DTO/User/UserRequestDTO.swift
  TnT/Projects/Domain/Sources/DTO/User/UserResponseDTO.swift
  TnT/Projects/Domain/Sources/Repository/UserRepository.swift
Labels: ✨Feat

#39 [TNT-142] 도메인 UI 분리 재병합, 전체적인 모듈 체크
  TnT/Projects/DesignSystem/Sources/Components/PopUp/TPopUpAlertState.swift
  TnT/Projects/DesignSystem/Sources/Constants/TrainingPurposeText.swift
  TnT/Projects/DesignSystem/Sources/Constants/UserTypeText.swift
  TnT/Projects/Domain/Sources/Entity/TrainingPurpose.swift
  TnT/Projects/Domain/Sources/Entity/UnitType.swift
  TnT/Projects/Domain/Sources/Entity/UserType.swift
  TnT/Projects/Presentation/Sources/Onboarding/Trainee/TraineeBasicInfoInput/TraineeBasicInfoInputView.swift
Labels: 🛠️Fix

#30 [TNT-158] 트레이너 회원가입 UI 및 네비게이션 구현
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_apple.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_apple.imageset/IcnApple.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_apple.imageset/IcnApple@2x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_apple.imageset/IcnApple@3x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_kakao.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_kakao.imageset/_Icons Responsive.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_kakao.imageset/_Icons Responsive@2x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_kakao.imageset/_Icons Responsive@3x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_boom.imageset/Boom.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_boom.imageset/Boom@2x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_boom.imageset/Boom@3x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_boom.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_connectioncompletebackground.imageset/ConnectionCompleteBackground.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_connectioncompletebackground.imageset/ConnectionCompleteBackground@2x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_connectioncompletebackground.imageset/ConnectionCompleteBackground@3x.png
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Images/img_connectioncompletebackground.imageset/Contents.json
  TnT/Projects/DesignSystem/Sources/Button/TBottomButton.swift
  TnT/Projects/DesignSystem/Sources/Button/TButton.swift
  TnT/Projects/DesignSystem/Sources/DesignSystem/Image+DesignSystem.swift
  TnT/Projects/DesignSystem/Sources/Navigation/TNavigation.swift
  TnT/Projects/Presentation/Sources/Onbarding/Common/OnboardingFeature.swift
  TnT/Projects/Presentation/Sources/Onbarding/Common/OnboardingView.swift
  TnT/Projects/Presentation/Sources/Onbarding/Common/TermFeature.swift
  TnT/Projects/Presentation/Sources/Onbarding/Common/TermView.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Code/MakeInvitationCodeFeature.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Code/MakeInvitationCodeView.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Connection/ConnectedTraineeProfileFeature.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Connection/ConnectedTraineeProfileView.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Connection/ConnectionCompleteFeature.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Connection/ConnectionCompleteView.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Profile/TrainerSignUpCompleteFeature.swift
  TnT/Projects/Presentation/Sources/Onbarding/Trainer/Login/Profile/TrainerSignUpCompleteView.swift
  TnT/Projects/Presentation/Sources/Tabbar/TabInfo.swift
  TnT/Projects/TnTApp/Sources/ContentView.swift
Labels: ✨Feat

#43 [TNT-195] 신규 디자인 시스템 반영, TChip/TRecordCard 컴포넌트 작성
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_addition.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_addition.imageset/Size=26, Type=addtion.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_alarm.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_alarm.imageset/Size=24, Type=alarm.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_arrow_right.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_arrow_right.imageset/Size=32, Type=arrow_right.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_arrow_up.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_arrow_up.imageset/Size=32, Type=arrow_up.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_bomb.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_bomb.imageset/type=bomb.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_bomb_empty.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_bomb_empty.imageset/type=link.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_calendar.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_calendar.imageset/Size=24, Type=calendar.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_check_box_selected.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_check_box_selected.imageset/Type=check fill_large, Status=true.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_check_box_unselected.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_check_box_unselected.imageset/Type=check fill_large, Status=false.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_clock.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_clock.imageset/Size=16, Type=clock.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_delete_24.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_delete_24.imageset/Size=24, Type=delete.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_elipses.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_elipses.imageset/Size=32, Type=3 dot.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_image.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_image.imageset/Size=26, Type=image.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_plus.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_plus.imageset/Size=24, Type=add.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_schedule.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_schedule.imageset/type=Schedule.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_search.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_search.imageset/Size=24, Type=search.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_star_smile.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_star_smile.imageset/Size=24, Type=smile.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_start_empty.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_start_empty.imageset/Size=16, Type=star.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_substraction.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_substraction.imageset/Size=26, Type=subtraction.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_down.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_down.imageset/icn_drop_down.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_left_32.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_left_32.imageset/Size=32, Type=arrow-left.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_right.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_right.imageset/Size=16, Type=arrow_right.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_right_32.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_triangle_right_32.imageset/Size=32, Type=arrow-right.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_warning.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_warning.imageset/warning.svg
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_write_black_filled.imageset/Contents.json
  TnT/Projects/DesignSystem/Resources/Assets.xcassets/Icons/icn_write_black_filled.imageset/Size=16, Type=write.svg
  TnT/Projects/DesignSystem/Sources/Components/Card/TRecordCard.swift
  TnT/Projects/DesignSystem/Sources/Components/Chip/TChip.swift
  TnT/Projects/DesignSystem/Sources/DesignSystem/Font+DesignSystem.swift
  TnT/Projects/DesignSystem/Sources/DesignSystem/Image+DesignSystem.swift
  TnT/Projects/Domain/Sources/Entity/MealType.swift
  TnT/Projects/Domain/Sources/Entity/RecordType.swift
  TnT/Projects/Domain/Sources/Entity/WorkoutType.swift
  TnT/Projects/Presentation/Sources/PresentationSupport/MealType.swift
  TnT/Projects/Presentation/Sources/PresentationSupport/RecordType.swift
Labels: ✨Feat
